"""add_cascade_delete_to_api_keys

Revision ID: a30d2f03de98
Revises: f5cb7603916b
Create Date: 2026-01-02 16:50:57.191991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'a30d2f03de98'
down_revision: Union[str, None] = 'f5cb7603916b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('crawl_jobs_api_key_id_fkey', 'crawl_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'crawl_jobs', 'api_keys', ['api_key_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('search_queries_api_key_id_fkey', 'search_queries', type_='foreignkey')
    op.create_foreign_key(None, 'search_queries', 'api_keys', ['api_key_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'search_queries', type_='foreignkey')
    op.create_foreign_key('search_queries_api_key_id_fkey', 'search_queries', 'api_keys', ['api_key_id'], ['id'])
    op.drop_constraint(None, 'crawl_jobs', type_='foreignkey')
    op.create_foreign_key('crawl_jobs_api_key_id_fkey', 'crawl_jobs', 'api_keys', ['api_key_id'], ['id'])
    # ### end Alembic commands ###
